"""initial tables

Revision ID: 0afa2f3d23de
Revises: 
Create Date: 2022-04-30 18:25:26.767363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afa2f3d23de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph',
    sa.Column('graph_id', sa.String(), nullable=False),
    sa.Column('qnt_connections', sa.Integer(), nullable=False),
    sa.Column('qnt_noh', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('graph_id')
    )
    op.create_table('path',
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_table('graph_path',
    sa.Column('graph_path_id', sa.String(), nullable=False),
    sa.Column('graph_id', sa.String(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.graph_id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['path.path_id'], ),
    sa.PrimaryKeyConstraint('graph_path_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_path')
    op.drop_table('path')
    op.drop_table('graph')
    # ### end Alembic commands ###
