"""alteration in graph_path, id is nullable

Revision ID: 544b1e32030b
Revises: 0afa2f3d23de
Create Date: 2022-04-30 20:09:15.712442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544b1e32030b'
down_revision = '0afa2f3d23de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graph_path', 'graph_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('graph_path', 'path_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graph_path', 'path_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('graph_path', 'graph_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
